### ISSUE TITLE
Authentication, how?

### ISSUE THREAD

**Issue by gmorchio** [angryelectron/xbmq#3]
Dear all:

I have installed your gateway, but my mqtt broker needs authentication, how can I do it with yours?

I've tried to put it before the address, but doesn't work.
No doc about though.

Can you help me?

Thanks!

**Comment by TeachingBudha** [comment]
I remember I did mine easily, just modifying the config file. Something
like user@broker -pass

**Comment by abythell** [comment]
Hi -

Authentication is not supported, but it could be added without too much difficulty.

In Xmbq.java:75, add additional options for username and password. See [MqttConnectOptions](http://www.eclipse.org/paho/files/javadoc/index.html) doc.  The username and password can be loaded from the properties file and used to build the options object by enhancing the `XbmqConfig` class.

If you're able to use Node.js instead of Java, consider using [xbmq-js](https://github.com/angryelectron/xbmq-js) instead, which has authentication support, documentation, is much lighter weight, and is more actively developed.

**Comment by angryelectron** [comment]
#4
