### ISSUE TITLE
rootTopic/gw/xbee/atIn Disconnects Bridge 

### ISSUE THREAD

**Issue by VoidVii** [angryelectron/xbmq#6]
rootTopic/gw/xbee/atIn
When i try do use the command **rootTopic/gw/xbee/atIn** with **D3** to check or **D3=3** to set it only throws out the **INFO: Connection restored into the log.** 

Anyone an idea why?

**Comment by abythell** [comment]
I'd recommend using something other than this project to achieve your goals if possible.  The [xbmq-js project](https://github.com/angryelectron/xbmq-js) is a newer, better implementation of the same thing, using Node.js instead of Java.
You can also build super-simple MQTT-to-XBee gateways with Node-Red using the `xbee-api` node and the `mqtt` nodes.  If you don't need to handle all the XBEE API commands, this is a nice, fast way to go.

If those aren't options for you, then here are some things to try.  

1. Confirm all the XBee Radios are in API mode (AP=2) and can communicate with each other (via XCTU, for example).
2. Publish a message to another topic to determine if all topics cause a disconnect, or just `atIn`.
3. Use `mosquitto_sub` (or similar debugging tool) to subscribe to the topic and see what type of message XBMQ is publishing there.

If you find anything interesting, feel free to post it here and I can try to take a closer look.

**Comment by Rezcue** [comment]
HI
i tried to switch to the xbmq.js now. 
Im having problems to intall it. Could u help me out?
Configure xbmq with your mqtt and serial port settings using command-line arguments. The arguments and their default values are: 
how do i use those commands the right way to configure my xbmq?

**Comment by VoidVii** [comment]
Im trying to switch ti xbmq.js and having sometrouble to isntall it. Can u please help me out?

Im following those steps.
npm install xbmq

npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ xbmq@2.0.5
updated 1 package in 10.995s

5 packages are looking for funding
  run `npm fund` for details


cd /home/pi/node_modules/xbmq
nano config.json.sample
{
    "rootTopic" : "XBeeS2C",
    "broker" : "mqtt://192.168.0.7.1883:",
    "username" : null,
    "password" : null,
    "port" : "/dev/ttyUSB0",
    "baud" : 9600,
    "log" : "./xbmq.log",
    "loglevel" : "info",
    "apiMode" : 2
}



renaming the config.json.sample to config.json
then 
./xbmq.js
/home/pi/node_modules/xbmq/node_modules/winston-transport/legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (/home/pi/node_modules/xbmq/node_modules/winston-transport/legacy.js:18:11)
    at DerivedLogger.add (/home/pi/node_modules/xbmq/node_modules/winston/lib/winston/logger.js:345:11)
    at Object.winston.<computed> [as add] (/home/pi/node_modules/xbmq/node_modules/winston/lib/winston.js:110:68)
    at Object.<anonymous> (/home/pi/node_modules/xbmq/lib/logger.js:4:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)

**Comment by abythell** [comment]
Fixed in [xbmq-js v2.0.6](https://www.npmjs.com/package/xbmq/v/2.0.6).    Other issues with xbmq-js can be reported [here](https://github.com/angryelectron/xbmq-js/issues).
